# Generated by Django 5.1.7 on 2025-04-02 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
