# Generated by Django 5.1.7 on 2025-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_notifications_user_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
